//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lmEntities : DbContext
    {
        public lmEntities()
            : base("name=lmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<td_Menu_B> td_Menu_B { get; set; }
        public virtual DbSet<td_News> td_News { get; set; }
        public virtual DbSet<td_Project> td_Project { get; set; }
        public virtual DbSet<td_TeamPeople> td_TeamPeople { get; set; }
        public virtual DbSet<td_Menu_A> td_Menu_A { get; set; }
        public virtual DbSet<td_Articles> td_Articles { get; set; }
        public virtual DbSet<td_Dictionary> td_Dictionary { get; set; }
        public virtual DbSet<td_CompanyInfo> td_CompanyInfo { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
