//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lmEntities : DbContext
    {
        public lmEntities()
            : base("name=lmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<tb_ClientMessage> tb_ClientMessage { get; set; }
        public virtual DbSet<tb_CompanyInfo> tb_CompanyInfo { get; set; }
        public virtual DbSet<tb_Menu_A> tb_Menu_A { get; set; }
        public virtual DbSet<tb_Menu_B> tb_Menu_B { get; set; }
        public virtual DbSet<tb_Project> tb_Project { get; set; }
        public virtual DbSet<tb_TeamPeople> tb_TeamPeople { get; set; }
        public virtual DbSet<Sys_LOG> Sys_LOG { get; set; }
        public virtual DbSet<tb_NewsCenter> tb_NewsCenter { get; set; }
        public virtual DbSet<tb_Dictionary> tb_Dictionary { get; set; }
    }
}
