//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Articles
    {
        public int ID { get; set; }
        public int ArticlesType { get; set; }
        public string ArticlesContent { get; set; }
        public string ArticlesTitle { get; set; }
        public System.DateTime Creationtime { get; set; }
        public string ImgPath { get; set; }
    }
}
