//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CompanyInfo
    {
        public int Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string Company_Call { get; set; }
        public string Company_Email { get; set; }
        public string Company_Description_T { get; set; }
        public string Company_description { get; set; }
        public string Company_WorkTime { get; set; }
        public string Company_AddersImgUrl { get; set; }
        public string Company_LogoUrl { get; set; }
        public string Company_copyright { get; set; }
    }
}
