//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ClientMessage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public bool IsDelete { get; set; }
        public bool IsDisplay { get; set; }
        public bool IsLook { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
    }
}
