//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Menu_A
    {
        public int menu_Id { get; set; }
        public string menu_Code { get; set; }
        public string menu_Name { get; set; }
        public string menu_FatherId { get; set; }
        public string menu_Link { get; set; }
        public string menu_Image { get; set; }
        public string menu_Title { get; set; }
        public string menu_Target { get; set; }
        public Nullable<int> menu_Sort { get; set; }
        public int menu_Stage { get; set; }
        public string menu_Note { get; set; }
    }
}
