//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UploadFile
    {
        public int Id { get; set; }
        public Nullable<int> DirId { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string Path_sm { get; set; }
        public Nullable<int> Uploader { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> FileType { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
