//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_News
    {
        public int Id { get; set; }
        public string News_Title { get; set; }
        public System.DateTime News_Date { get; set; }
        public int News_People { get; set; }
        public string News_Content { get; set; }
        public Nullable<int> News_CommentariesID { get; set; }
        public int News_ImgId { get; set; }
        public System.DateTime News_CDate { get; set; }
    }
}
